{% set name = "chainladder" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chainladder-{{ version }}.tar.gz
  sha256: 97e8b8a79d3a5fa54c6a432761985e50f531ed15f491617ee6d58403b8346907

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=2.3.3,<=3.0.3
    - numpy >=2.0
    - scikit-learn >1.4.2
    - sparse >=0.9
    - matplotlib-base
    - dill
    - patsy >=1.0.2
    - joblib
    - scipy

test:
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  license: MPL-2.0
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
    - kennethshsu
